import { getTopologicalOrder, topicsBySlug } from "@/lib/learning/graph";
import { loadStoredMasteries, loadDiagnosticResult } from "@/lib/storage/progress-store";
import { computeOverallMasteryPercentage } from "@/lib/mastery/mastery-engine";
import { generatePersonalizedPath } from "@/lib/learning/personalized-path";
import { dsaTopics } from "@/data/dsa/topics";
import { cyberTopics } from "@/data/cybersecurity/topics";

export function generateMarkdownRoadmap(domain: "dsa" | "cybersecurity"): string {
  const isCyber = domain === "cybersecurity";
  const topics = isCyber ? cyberTopics : dsaTopics;
  const masteries = loadStoredMasteries(domain);
  const diagnostic = loadDiagnosticResult(domain);
  const stats = computeOverallMasteryPercentage(masteries, topics);
  const personalized = generatePersonalizedPath(masteries, domain);
  const orderedTopics = getTopologicalOrder(domain);

  const title = isCyber
    ? "Cybersecurity & Defensive Engineering Roadmap"
    : "Data Structures & Algorithms (DSA) Roadmap";

  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let md = `# ${title}\n`;
  md += `**Generated by Techla.labs.learn on ${date}**\n\n`;
  md += `---\n\n`;

  // Section 1: Progress & Diagnostic Overview
  md += `## 1. Overall Progress & Mastery\n\n`;
  md += `- **Curriculum Mastery**: ${stats.percentage}%\n`;
  md += `- **Mastered Topics**: ${stats.masteredCount} / ${stats.totalTopics}\n`;
  md += `- **In Progress**: ${stats.learningCount}\n`;
  md += `- **Ready to Unlock**: ${personalized.recommendedTopics.length}\n`;

  if (diagnostic) {
    md += `- **Latest Diagnostic Score**: ${diagnostic.score} / ${diagnostic.totalQuestions} (${diagnostic.percentage}%)\n`;
  }
  md += `\n---\n\n`;

  // Section 2: Immediate Next Steps
  md += `## 2. Immediate Recommended Next Steps\n\n`;
  if (personalized.recommendedTopics.length > 0) {
    personalized.recommendedTopics.slice(0, 5).forEach((t, idx) => {
      const reasonObj = personalized.reasoning.find((r) => r.topicSlug === t.slug);
      const reason = reasonObj?.reason || "Next logical prerequisite node.";
      md += `### ${idx + 1}. ${t.title} (${t.category})\n`;
      md += `- **Estimated Time**: ${t.estimatedMinutes} minutes\n`;
      md += `- **Why Next**: ${reason}\n`;
      md += `- **Objective**: ${t.masteryCriteria}\n\n`;
    });
  } else {
    md += `All foundational and intermediate nodes have been mastered!\n\n`;
  }

  md += `---\n\n`;

  // Section 3: Full Topological Curriculum
  md += `## 3. Full Sequenced Curriculum Graph\n\n`;
  orderedTopics.forEach((t, idx) => {
    const mastery = masteries[t.slug]?.masteryLevel ?? 0;
    let statusIcon = "🔒 Locked";
    if (mastery >= 4) statusIcon = "✅ Mastered (Level " + mastery + "/5)";
    else if (mastery >= 2) statusIcon = "🔄 In Progress (Level " + mastery + "/5)";
    else if (t.prerequisites.length === 0 || t.prerequisites.every((p) => (masteries[p]?.masteryLevel ?? 0) >= 3)) {
      statusIcon = "⚡ Available to Learn";
    }

    const prereqTitles = t.prerequisites
      .map((p) => topicsBySlug[p]?.title || p)
      .join(", ") || "None (Foundational)";

    md += `### Step ${String(idx + 1).padStart(2, "0")}: ${t.title}\n`;
    md += `- **Category**: ${t.category}\n`;
    md += `- **Status**: ${statusIcon}\n`;
    md += `- **Prerequisites**: ${prereqTitles}\n`;
    md += `- **Summary**: ${t.summary}\n`;
    md += `- **Key Concepts**: ${t.keyConcepts.join(", ")}\n\n`;
  });

  md += `---\n\n`;
  md += `*Keep learning and testing at https://app.techla.labs/learn/${domain}*\n`;

  return md;
}

export function downloadRoadmapFile(domain: "dsa" | "cybersecurity", format: "md" | "json" = "md"): void {
  if (typeof window === "undefined") return;

  let content = "";
  let filename = "";
  let mimeType = "";

  if (format === "md") {
    content = generateMarkdownRoadmap(domain);
    filename = `techla-${domain}-roadmap-${new Date().toISOString().split("T")[0]}.md`;
    mimeType = "text/markdown;charset=utf-8";
  } else {
    const backup = {
      domain,
      exportedAt: new Date().toISOString(),
      masteries: loadStoredMasteries(domain),
      diagnostic: loadDiagnosticResult(domain),
    };
    content = JSON.stringify(backup, null, 2);
    filename = `techla-${domain}-backup-${new Date().toISOString().split("T")[0]}.json`;
    mimeType = "application/json;charset=utf-8";
  }

  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
